### ISSUE TITLE
Running on Synology

### ISSUE THREAD

**Issue by haldi4803** [maxisoft/Freenom-dns-updater#35]
Hi,
Years back i used this on Synology in a Docker.
`sudo docker run \
    -v /volume2/docker/Freenom-updater/etc:/etc\
    --rm \
    --name FreenomDNSupdater\
    maxisoft/freenom-dns-updater:latest \
fdu process\
sudo docker stop maxisoft/freenom-dns-updater:latest`
Worked fine. Now that doesn't work anymore...

So i've tried to install this directly.

`sudo python3 -m pip install freenom-dns-updater
Collecting freenom-dns-updater
  Downloading freenom_dns_updater-1.2.9-py3-none-any.whl (25 kB)
Collecting requests
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 924 kB/s
Collecting click
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 256 kB/s
Collecting oscrypto
  Downloading oscrypto-1.2.1-py2.py3-none-any.whl (192 kB)
     |████████████████████████████████| 192 kB 15.4 MB/s
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
     |████████████████████████████████| 115 kB 51.5 MB/s
Collecting six
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting PyYAML
  Downloading PyYAML-5.4.1-cp38-cp38-manylinux1_x86_64.whl (662 kB)
     |████████████████████████████████| 662 kB 51.7 MB/s
Collecting soupsieve>1.2
  Downloading soupsieve-2.2.1-py3-none-any.whl (33 kB)
Collecting asn1crypto>=1.0.0
  Downloading asn1crypto-1.4.0-py2.py3-none-any.whl (104 kB)
     |████████████████████████████████| 104 kB 50.0 MB/s
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
     |████████████████████████████████| 153 kB 49.9 MB/s
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 46.3 MB/s
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 1.6 MB/s
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 49.0 MB/s
Installing collected packages: urllib3, soupsieve, idna, chardet, certifi, asn1crypto, six, requests, PyYAML, oscrypto, click, beautifulsoup4, freenom-dns-updater
  WARNING: The script chardetect is installed in '/var/packages/py3k/target/usr/local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script fdu is installed in '/var/packages/py3k/target/usr/local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed PyYAML-5.4.1 asn1crypto-1.4.0 beautifulsoup4-4.9.3 certifi-2020.12.5 chardet-4.0.0 click-7.1.2 freenom-dns-updater-1.2.9 idna-2.10 oscrypto-1.2.1 requests-2.25.1 six-1.15.0 soupsieve-2.2.1 urllib3-1.26.4
Haldi@NAS:~$ fdu
-sh: fdu: command not found`

Added that to path...
`Haldi@NAS:~$ source /etc/profile
Haldi@NAS:~$ echo $PATH | tr ":" "\n" | nl
     1  /sbin
     2  /bin
     3  /usr/sbin
     4  /usr/bin
     5  /usr/syno/sbin
     6  /usr/syno/bin
     7  /usr/local/sbin
     8  /usr/local/bin
     9  /var/packages/py3k/target/usr/local/bin`

and now i'm getting this:
`Haldi@NAS:~$ fdu
Traceback (most recent call last):
  File "/var/packages/py3k/target/usr/local/bin/fdu", line 5, in <module>
    from freenom_dns_updater.scripts.fdu import cli
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/freenom_dns_updater/__init__.py", line 2, in <module>
    from .config import Config
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/freenom_dns_updater/config.py", line 11, in <module>
    from .encrypted_string import EncryptedString
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/freenom_dns_updater/encrypted_string.py", line 5, in <module>
    from oscrypto.symmetric import aes_cbc_pkcs7_decrypt, aes_cbc_pkcs7_encrypt
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/oscrypto/symmetric.py", line 43, in <module>
    from ._openssl.symmetric import (
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/oscrypto/_openssl/symmetric.py", line 8, in <module>
    from ._libcrypto import libcrypto, LibcryptoConst, handle_openssl_error
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/oscrypto/_openssl/_libcrypto.py", line 15, in <module>
    from ._libcrypto_ctypes import (
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/oscrypto/_openssl/_libcrypto_ctypes.py", line 28, in <module>
    raise LibraryNotFoundError('The library libcrypto could not be found')
oscrypto.errors.LibraryNotFoundError: The library libcrypto could not be found`

something wen't wrong right?...

**Comment by benthetechguy** [comment]
Your message is very hard to read since you put it into a code snippet instead of a code block, blending all the lines into one.
Regardless, did you actually read the error? The last sentence contains the exact information you need. You need to have `libcrypto` installed.
